### ISSUE TITLE
having difficulty using it, help wanted

### ISSUE THREAD

**Issue by netstrem** [micahmo/m3u8restreamer#1]
Hi. I've been having some difficulties using this.
I've gotten the docker container to run in Qemu, but I'm confused about the `Usage` portion.

<br/>

-  It says to replace **ALL** forward slashes in the original stream URL, however in your example, the only forward slashes that are replaced in the original stream URL are the two after `http:` (in `getStream/http://`, not replacing the one before `name.m3u8`).

```
#EXTM3U

#EXTINF:-1,CHANNELNAME
http://192.168.1.2:11034/getStream/http:%2F%2Foriginal.stream.com/name.m3u8
```

Is it thus supposed to be like this instead?

```
#EXTM3U

#EXTINF:-1,CHANNELNAME
http://192.168.1.2:11034/getStream/http:%2F%2Foriginal.stream.com%2Fname.m3u8
```

- What link points to the restreamed .m3u file? Would it be something such as:

> http://192.168.1.2:11034/news.m3u

if my m3u file was named `news.m3u`? And would the restreamer automatically detect the .m3u file? 

Thank you in advance for your assistance.

**Comment by micahmo** [comment]
Hey @netstrem, good question. The wording in the README ("replace all forward slashes") is not quite right, but the example is. You only need to replace the forward slashes in the protocol (`http://` -> `http:%2F%2F`), but any other forward slashes in the URL are fine.

> What link points to the restreamed .m3u file? Would it be something such as: http://192.168.1.2:11034/news.m3u if my m3u file was named news.m3u? And would the restreamer automatically detect the .m3u file?

I'm not sure I completely understand this question. The way it works is that you invoke the `getStream` endpoint, providing another URL as the parameter, and, in response, you get the chunks streamed back to you. That way, the service is completely generic (in other words, you don't have to do any setup ahead of time). Whatever URL you pass, it streams back.

Let's take an example. I hope you don't mind, but I poked around your repository and found this URL: `https://raw.githubusercontent.com/netstrem/offline-video/main/unavailable_generic.m3u`. If m3u8restreamer were running on `192.168.1.2` port `11034`, then the new URL would be `http://192.168.1.2:11034/getStream/https:%2F%2Fraw.githubusercontent.com/netstrem/offline-video/main/unavailable_generic.m3u`.

To complete the example, I would add that to an `.m3u` file for xTeVe.

```
#EXTM3U

#EXTINF:1,TEST
http://192.168.1.2:11034/getStream/https:%2F%2Fraw.githubusercontent.com/netstrem/offline-video/main/unavailable_generic.m3u
```

And then I would point Plex at the xTeVe tuner, and it would work!

I picked a random channel (Smithsonian) for the guide data, but otherwise your stream plays fine in Plex.

| ![image](https://user-images.githubusercontent.com/7417301/185769756-333c8af6-c00a-45c7-84b6-89ccc56bbd2e.png) |
| - |

I should mention that this scenario (m3u8 -> xTeVe -> Plex) is the only one that I've tested and used. In fact, if I invoke m3u8restreamer from another application that can otherwise read m3u8 streams (like VLC or Streamlink) it doesn't seem to work very well. There's some magic about it going through xTeVe and Plex that just works. 😊

**Comment by netstrem** [comment]
Thank you for your quick response, I understand now to only replace the forward slashes in the protocol and how `getStream` works.

As for xTeVe, I've never tried it with Plex. I was looking to utilize this for use in stream players, particularly Perfect Player on Android, as that is the m3u player I use. It's a shame if it doesn't work well in it then.

Nonetheless, thank you once again for your assistance, much appreciated!

**Comment by micahmo** [comment]
Hey, sorry that this tool may not be exactly what you were looking for! To be honest I've never really had an issue with players that are intended to play m3u/m3u8. Although I've never used Perfect Player, apps like VLC generally handle streams fine (like your `https://raw.githubusercontent.com/netstrem/offline-video/main/unavailable_generic.m3u`).

Good luck!
